### PR TITLE
fix: remove font tags

### PR DESCRIPTION
**Pull request by Meschreiber**
When we were using the package we noticed a lot of captions like this: `backup<font color="#CCCCCC"> ran successfully and that bit is</font>`

My regex is terrible, feel free to prettify

### CODE REVIEW

**Comment by iam4x** [comment]
Nice thanks, I'll be happy to help you for the regex. What is the videoId you had the issue?

**Comment by Meschreiber** [comment]
It happened with all or almost all actually

image

**Comment by iam4x** [comment]
This might be a bigger issue, we should remove any html tags. Can you try to use https://www.npmjs.com/package/striptags?

--
Maxime Janton
Software Engineer
+33 6 81 82 00 12

**Comment by utay** [comment]
You pushed your `package-lock.json` @Meschreiber haha
Otherwise LGTM! 👍

**Comment by Meschreiber** [comment]
ugh, so embarrassing :P

**Pull request merged**
